# Uncomment the next line to define a global platform for your project
platform :ios, '17.6'

def framework_pods
  use_frameworks!
  pod 'Alamofire'
  pod 'PromiseKit', '~> 6.10'
  pod 'PromiseKit/Alamofire'
  pod 'ActiveLabel'
  pod 'SDWebImage'
  pod 'SwiftMessages'
  pod 'PhoneNumberKit', '~> 3.3'
  pod 'KeychainSwift', '~> 19.0'
  pod 'TinyConstraints'
#  pod 'Firebase/Crashlytics'
end

target 'Glyanec' do
  framework_pods
end

target 'GlyanecTests' do
  framework_pods
end

target 'GlyanecUITests' do
  framework_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.6'
    end
  end
end
